# Site specific settings
title: "robots.txt"
name: "robots.txt"
keywords: "Key, words, about, this, website"
baseurl: "/robots_txt"
url: "https://het-joshi.github.io"
description: "My cybersecurity blog. An effort to document my learning journey, projects and thoughts."
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: jetjoshi
twitter: 
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
